name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Supabase v1.100.1
        uses: supabase/setup-cli@v1
        with:
          version: 1.100.1
      - name: Install dependencies
        run: bun install
      - name: Start database
        run: |
          supabase start
          supabase db reset
      - name: Set environment variables
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 1
          command: |
            supabase status --output env | node scripts/convert_env.js > .env
            test -s .env
      - name: Lint code style
        run: bun run lint
  compare-remote-db:
    runs-on: ubuntu-latest
    env:
      # Setting an environment variable with the value of a configuration variable
      DB_URL: ${{ secrets.DB_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Supabase v1.100.1
        uses: supabase/setup-cli@v1
        with:
          version: 1.100.1
      - name: Install dependencies
        run: bun install
      - name: Start database
        run: |
          supabase db start
          supabase db reset
      - name: Verify generated types match Postgres schema
        run: |
          bun run update-types
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/lib/supabase.ts; then
              echo "Detected uncommitted changes after build. See status below:\n" >> $GITHUB_STEP_SUMMARY
              echo '```diff' >> $GITHUB_STEP_SUMMARY
              echo $(git diff) >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              exit 1
          fi
      - name: (main only) Ensure there are no unpushed migrations
        run: |
          if supabase migration list --db-url $DB_URL | grep -E '\s*(\d+) │ \s+ │ .+$'; then
            echo "Unpushed migrations detected:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "$(supabase migration list --db-url $DB_URL | grep -E '\s*(\d+) │ \s+ │ .+$' --color=never)" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
